// User reducer types
export const SET_FINGERPRINT = 'SET_FINGERPRINT';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_SNIPPETS = 'SET_SNIPPETS';
export const SET_SNIPPETS_NAV = 'SET_SNIPPETS_NAV';
export const SET_SNIPPET = 'SET_SNIPPET';
export const PLAY_SNIPPET = 'PLAY_SNIPPET';
export const LIKE_SNIPPET = 'LIKE_SNIPPET';
export const UNLIKE_SNIPPET = 'UNLIKE_SNIPPET';
export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const POST_SNIPPET = 'POST_SNIPPET';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
// Audio reducer types
export const SET_PLAYING_SNIPPET = 'SET_PLAYING_SNIPPET';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const ENCODE_AUDIO_FILE = 'ENCODE_AUDIO_FILE';
export const ENCODING_AUDIO_FILE = 'ENCODING_AUDIO_FILE';
export const SET_ENCODED_FILE = 'SET_ENCODED_FILE'